### ISSUE TITLE
Implement a check if the domain resolves

### ISSUE THREAD

**Issue by 0xc0ffeee** [arbazkiraak/BurpBLH#1]
Hi, thank you for your great extension. 

Is there a way to check if the domain does not exist so we could register it and hijack the link? 
From what I tested, this extension only checks if the link does not give a 200, right? I know we have the whitelist but I think it would be good to check for DNS resolution! I maybe could work on this.

**Comment by arbazkiraak** [comment]
Hi @0xc0ffeee ,

* We can add an resolution to look for `expired` domains or subdomains, But we can't really define the differences if they are from third-party services like `Amazon,Github Pages etc`, unless we add an fingerprint for all possible services.

* I Will see what i can do with it in next update.

Thanks~

**Comment by arbazkiraak** [comment]
Resolving added.
